# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: 
  contents: write
  pages: write
  id-token: write
  checks: write
  deployments: write 
  actions: write
  packages: write
  repository-projects: write
  billing: write
  discussions: write
  graphql: write
  pull-requests: write
  repository-vulnerabilities: write
  security-events: write
  codespaces: write
  marketplaces: write
  sponsorships: write 
  members: write
  team-discussions: write
  users: write
  user-status: write
  public-key-credentials: write
  registry: write

  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages 
        uses: actions/configure-pages@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with: 
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  test:  
    needs: build
    runs-on: ubuntu-latest  
    steps:
      - name: Test Site
        run: jekyll build --future

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deploy  
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}  
      - name: Notify Success 
        if: success()
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.create({
              owner: context.repo.owner, 
              repo: context.repo.repo,
              title: "Deployment Success",
              body: "Deployment was successful!"
            })
