name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

concurrency:
  group: pages-deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: pages-artifact  
          path: '.'
          retention-days: 5
        
      - name: Deploy to GitHub Pages
        id: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5 
        with:
          branch: gh-pages
          folder: '.' 
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: npm test
        
      - name: Health check
        run: curl -f ${{ steps.deploy.outputs.url }}
        
      - name: Retry on failure
        if: failure() 
        run: ${{ github.action_path }}
        continue-on-error: true
        max-attempts: 3

      - name: Create failure issue
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            const issue_title = "Deployment of static content failed"
            const issue_body = `Deployment was failed. Please check the deployment logs for diagnosis`
            console.log(issue_title) 
            console.log(issue_body)
            github.rest.issues.create({
             owner: context.repo.owner,
             repo: context.repo.repo,
             title: issue_title,
             body: issue_body,
           })

      - name: Success notification
        if: success()
        uses: actions/github-script@v3
        with:
          script: |
            const issue_title = "Deployment of static content successful"
            const issue_body = `Deployment was successful. Pages can be accessed here ${process.env.PAGE_URL}`
            console.log(issue_title)
            console.log(issue_body)
            github.rest.issues.create({
             owner: context.repo.owner,
             repo: context.repo.repo,
             title: issue_title,
             body: issue_body,
           })

    environment:
      name: github-pages  
      url: ${{ steps.deploy.outputs.url }}
